#!/bin/python

import dbus
import time
import notify

bus = dbus.SystemBus()

power = bus.get_object('org.freedesktop.UPower', '/org/freedesktop/UPower')
power_iface = dbus.Interface(power, dbus_interface='org.freedesktop.UPower')

display_device_path = power_iface.GetDisplayDevice()

dev       = bus.get_object('org.freedesktop.UPower', display_device_path)
dev_iface = dbus.Interface(dev, dbus_interface='org.freedesktop.DBus.Properties')

last_five = 200
charging = 0
while True:
    percentage = dev_iface.Get('org.freedesktop.UPower.Device', 'Percentage') + 0
    state = dev_iface.Get('org.freedesktop.UPower.Device', 'State')
    
    if (state == 1):
        last_five = 200
    if (percentage % 3 == 0):
        if (last_five == percentage):
            continue
        else:
            last_five = percentage
            notify.notification('Battery: {}'.format(percentage), message='discharging')
            print('Battery: {}'.format(percentage))
    time.sleep(1)
