;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-visual-line
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        end-of-visual-line
        forward-sexp
        haskell-indentation-common-electric-command
        helm-M-x
        indent-for-tab-command
        markdown-outdent-or-delete
        my-backward-delete-word
        my-delete-word
        org-self-insert-command
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        dap-tooltip-mouse-motion
        lsp-signature-activate
        mouse-drag-region-rectangle
        text-scale-adjust
        ))
