# [cursor]
# blink_interval = 2
# 
# [cursor.style]
# blinking = "On"
# shape = "Block"

[font]
# family = "monospace"
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[scrolling]
history = 100000

[window]
# capacity = 0.5
dynamic_title = true
opacity = 0.8

[window.padding]
x = 0
y = 0

# [general]
# live_config_reload = true
