#!/bin/bash

set -x

commands="add\nlist\ndone"

[ -z $1 ] && cmd=$(echo -e $commands | dmenu -i | xargs) || cmd=$1

case $cmd in
    "list")
        task rc.verbose=nothing list | awk '{printf "%s\t", $1 ; for (i=3; i<=NF-1; i+=1) {printf " %s", $i} ; printf "\t%s\n", $NF}' | yad --text-info --geometry=1200x800
        ;;
    "add")
        tags=$(task rc.verbose=nothing tags | tail -n +3 | head -n -1 | awk '{print $1}' | dmenu -i -p "category:" -l 10)
        [ -z $tags ] && notify-send "exiting" && exit
        desc=$(echo "" | dmenu -i -p "enter description:")
        [ -z $desc ] && notify-send "exiting" && exit
        due=$(echo -e "someday\nlater" | dmenu -i -p "due date:")
        [ -z $due ] \
            && task add "$desc" +"$tags" \
                || task add "$desc" +"$tags" due:"$due"
        kill -44 $(pgrep dwmblocks)
        ;;
    "done")
        done=$(task rc.verbose=nothing list | awk '{ for (i=5; i<NF; i+=1) { printf "%s ", $i } ; printf "\t%s", $1 ; printf "\n" }' | dmenu -i -l 20 -p "choose a task to complete:")
        [ -z $done ] && notify-send "exiting" && exit
        task done $(echo $done | awk '{print $NF}')
        notification=$(echo $done | awk '{ for (i=1; i<NF; i+=1) {printf "%s ", $i}}')
        notify-send "completed task:" "$notification"
        kill -44 $(pgrep dwmblocks)
        ;;
esac
