#!/usr/bin/env sh

set -x

SCRATCH="/tmp/scratch"
touch $SCRATCH

function help {
    echo -e "USAGE\n=====\n- $0"
    echo -e "  - push > add window to stack"
    echo -e "  - pop  > remove window to stack"
    exit
}

function push {
    WID=$(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | awk '{print $2}')
    WNAME=$(xwininfo -id "$WID" | grep xwininfo |\
                awk '{for (i=5; i<=NF; i++) printf "%s ",$i;}' |\
                cut -c 2- | head -c -3)
    echo "$WNAME"
    xdo hide $WID
    echo "$WID - $WNAME" >> $SCRATCH
    exit
}

function push_id {
    WID=$1
    WNAME=$(xwininfo -id "$WID" | grep xwininfo |\
                awk '{for (i=5; i<=NF; i++) printf "%s ",$i;}' |\
                cut -c 2- | head -c -3)
    echo "$WNAME"
    xdo hide $WID
    echo "$WID - $WNAME" >> $SCRATCH
    exit
}

function pop_wid {
    WID="$1"
    [ $(echo $WID | wc -w) -eq 0 ] && exit

    TMP=$(mktemp)
    grep -v $WID $SCRATCH > $TMP
    mv $TMP $SCRATCH
    xdo show $WID
    exit
}

function pop {
    WID=$(tail -n 1 $SCRATCH | awk '{print $1}')
    pop_wid $WID
}

function pop_named {
    LINE=$(cat $SCRATCH | dmenu)
    WID=$(echo $LINE | awk '{print $1}')
    pop_wid $WID
}

[ $# -eq 0 ] && help
[ "$1" = "push" ] && push
[ "$1" = "pop" ] && pop
[ "$1" = "pop_named" ] && pop_named
[ "$1" = "id" ] && push_id $2
