#!/usr/bin/env python

import sys
import subprocess

import json

if len(sys.argv) < 2:
   arg = "cyclenext"
else:
   arg = sys.argv[1]

def hyprctl(*args):
   result = subprocess.run(["hyprctl"] + list(args), capture_output=True, text=True)
   return result.stdout.strip()

active = json.loads(hyprctl("-j", "activewindow"))
active_addr = active["address"]
active_grouped = active["grouped"]

if active_grouped == []:
   hyprctl("dispatch", "layoutmsg", arg)
   exit(0)

# should never throw since we know we're part of the group
idx = active_grouped.index(active_addr)
if arg == "cyclenext":
   if idx == len(active_grouped) - 1:
      hyprctl("dispatch", "layoutmsg", "cyclenext")
   else:
      hyprctl("dispatch", "changegroupactive", "f")
elif arg == "cycleprev":
   if idx == 0:
        hyprctl("dispatch", "layoutmsg", "cycleprev")
   else:
        hyprctl("dispatch", "changegroupactive", "b")

new_active = json.loads(hyprctl("-j", "activewindow"))

if new_active["address"] == active_addr:
   if arg == "cyclenext":
      hyprctl("dispatch", "changegroupactive", "f")
   elif arg == "cycleprev":
      hyprctl("dispatch", "changegroupactive", "b")
