#!/bin/sh

# A dmenu wrapper script for system functions.

cmds="\
🔒 lock		slock
🚪 leave dwm	kill -TERM $(pgrep -u $USER "\bdwm$")
♻ renew dwm	kill -HUP $(pgrep -u $USER "\bdwm$")
🐻 hibernate	slock ${hib:-systemctl suspend-then-hibernate -i}
🔃 reboot	${reb:-reboot}
🖥 shutdown	${shut:-shutdown -h now}
📺 display off 	 xset dpms force off"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu)" || exit 1

eval "$(echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-)"
