#!/bin/env python

import json
import os
import sys

with open("/opt/discord/resources/build_info.json", "r") as f:
    content = f.read()

js = json.loads(content)
curnum = (js['version'].split(".")[2])
if len(sys.argv) == 1:
       curnum += 1
else:
       curnum = sys.argv[1]
js['version'] = f'0.0.{curnum}'
new_content = json.dumps(js, indent=True)

with open("/opt/discord/resources/build_info.json", "w") as f:
    f.write(new_content)
