#!/bin/bash

echo "$@"

# set -x

# Arbitrary but unique message id
msgId="991049"

case $1 in
    "input" )
        OPTIONS="--default-source"
        ;;
    "output" )
        OPTIONS=""
        ;;
    * )
        echo "first field must be either input or output. your first field was:"
        echo $1
        exit
        ;;
esac

echo $#

if [ "$#" -ne 2 ]; then
    echo "wrong number of fields"
    exit
fi

pamixer $OPTIONS --allow-boost --set-volume $2 > /dev/null

volume=$(pamixer $OPTIONS --get-volume)

time=2000

if [ $volume = 0 ]; then
    dunstify -a "changeVolume" -t $time -u low -i audio-volume-muted -r "$msgId" "Volume muted" 
else
    dunstify -a "changeVolume" -t $time -u low -i audio-volume-high -r "$msgId" -h int:value:"$volume" "Volume: ${volume}%"
fi

# Play the volume changed sound
canberra-gtk-play -i audio-volume-change -d "changeVolume"
